name: InstantSmelt
version: 1.0.13
author: Coleski123
main: me.coleski123.instantsmelt.InstantSmelt
api-version: 1.21
commands:
  instasmelt:
    description: Smelts the item in your hand!
    aliases: is
  instasmeltcost:
    description: Checks the current smelt cost.
    aliases: isc
  instasmeltconfig:
    description: Opens the config GUI.
    aliases: isconfig
  instasmeltall:
    description: Smelts all items of the same value in your inventory.
    aliases: is all
permissions:
  instasmelt.use:
    description: Allows player to use the InstaSmelt command
    default: op
  instasmelt.use.smeltcost:
    description: Allows the player to use the smelt cost command
    default: op
  instasmelt.use.gui.config:
    description: Allows the player to open the config GUI.
    default: op
  instasmelt.all:
    description: Allows the player to smell all items of their hand value in their inventory.
    default: op
