name: InstantSmelt
version: 0.9
author: Coleski123
main: me.coleski123.instantsmelt.InstantSmelt
api-version: 1.19
commands:
  instasmelt:
    description: Smelts the item in your hand!
    aliases: is
  smeltcost:
    description: Checks the current smelt cost.
    aliases: sc
  instasmeltconfig:
    description: Opens the config GUI.
    aliases: isc
permissions:
  instasmelt.use:
    description: Allows player to use the InstaSmelt command
    default: op
  instasmelt.use.smeltcost:
    description: Allows the player to use the smelt cost command
    default: op
  instasmelt.use.gui.config:
    description: Allows the player to open the config GUI.
    default: op
