name: InstantSmelt
version: '${project.version}'
author: Coleski123
main: me.coleski123.instantsmelt.InstantSmelt
api-version: 1.19
commands:
  instasmelt:
    description: Smelts the item in your hand!
  smeltcost:
    description: Checks the current smelt cost.
  instasmeltreload:
    description: Reloads the plugin.
permissions:
  instasmelt.use:
    description: Allows player to use the InstaSmelt command
    default: op
  instasmelt.use.smeltcost:
    description: Allows the player to use the smelt cost command
    default: op
  instasmelt.use.reload:
    description: Allows the player to reload the plugin
    default: op
